### ISSUE TITLE
Request for admin privileges on startup

### ISSUE THREAD

**Issue by verybadsoldier** [marciomarim/zlobby#3]
Hey Zorro,

on my machine Zlobby is asking for admin priviliges on every start. I am on Windows 10 H2. I already reinstalled it completely.
This isn't supposed to happen, right?
Any ideas what could cause it?

Thank you!

**Comment by marciomarim** [comment]
Hi vbs,

Windows requires apps to be signed with a paid certificate so it's kinda supposed to happen in some recent Windows versions. I'll be adding a certificate to sign the .exe and solve this "trust issue", but I didnt had time to do it yet sorry.

Meanwhile you can whitelist the app (I think you'll find searching for "Add an exclusion to Windows Security")

Cheers!

**Comment by marciomarim** [comment]
Hi vbs,

Windows requires apps to be signed with a paid certificate so it's kinda supposed to happen in some recent Windows versions. I'll be adding a certificate to sign the .exe and solve this "trust issue", but I didnt had time to do it yet sorry.

Meanwhile you can whitelist the app (I think you'll find searching for "Add an exclusion to Windows Security")

Cheers!

**Comment by verybadsoldier** [comment]
Hm, tbh I think it is something different. I think it really asks for elevated privileges (admin privileges). Not for something like "do you really want to run this unsecure application?". I don't think Windows automatically would elevate those privileges _because_ the application is untrusted? Would seems counter productive wrt security.

Something like this:
https://answers.microsoft.com/en-us/windows/forum/windows_8-files/applications-continue-to-ask-if-i-want-it-to-make/89c75a43-67bc-4a27-acb4-f5ee1cb2ae5f?auth=1

**Comment by marciomarim** [comment]
Ok I think I found the issue, it should be solved on next release.

**Comment by verybadsoldier** [comment]
Yes I can confirm it is solved, thanks!

Just out of curiosity: was it related to the missing certificate or was it something else?

**Comment by marciomarim** [comment]
Hi vbs, 
It was a misconfiguration in the package.json to be more specific it was the requestedExecutionLevel parameter that should be removed, sorry :/

**Comment by verybadsoldier** [comment]
No need to feel sorry, as being a software developer myself I really just wanted to learn the root cause. Thank you!
