### ISSUE TITLE
Map not found when launching

### ISSUE THREAD

**Issue by verybadsoldier** [marciomarim/zlobby#4]
I tried to join the game but engine says it cannot find the map. As far as I can see zlobby think it is available?

![image](https://user-images.githubusercontent.com/364469/115089526-ad42dc80-9f12-11eb-9b7b-63d133d32f8f.png)

Maybe I am doing something wrong?
I tried several times, also restarted zlobby.

**Comment by marciomarim** [comment]
Is it possible it was still downloading that map? It shouldnt show as available before download finishes but I can't see any other reason so far.

**Comment by marciomarim** [comment]
Or maybe that map didn't fully downloaded. Can you delete the file and let the lobby get it again to see if that was the issue?

**Comment by verybadsoldier** [comment]
Yes I think you are right, the file 
`C:\Users\xxx\Documents\My Games\Spring\maps\dsdr_4.0.sd7`

seems not to be a valid 7z archive. I'll delete it and see what happens! Thanks!

**Comment by marciomarim** [comment]
Added a check_map_size to detect map corruption, it will delete and download again if local file is corrupted. Also added manual buttons "Recheck Map" and "Recheck Game" to force it from battleroom if needed.
